{ pkgs, ... }:

{
  # Run unpatched, dynamically linked binaries (prebuilt tools, language-server downloads, ...).
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      SDL
      SDL2
      SDL2_image
      SDL2_mixer
      SDL2_ttf
      SDL_image
      SDL_mixer
      SDL_ttf
      acl
      alsa-lib
      at-spi2-atk
      at-spi2-core
      atk
      attr
      bzip2
      cairo
      cups
      curlWithGnuTls
      curl
      dbus
      dbus-glib
      desktop-file-utils
      e2fsprogs
      expat
      flac
      fontconfig
      freeglut
      freetype
      fribidi
      fuse
      fuse3
      gdk-pixbuf
      glew
      glew_1_10
      glib
      gmp
      gst_all_1.gst-plugins-base
      gst_all_1.gst-plugins-ugly
      gst_all_1.gstreamer
      gtk2
      harfbuzz
      gtk3
      icu
      keyutils.lib
      libGL
      libGLU
      libappindicator
      libcaca
      libcanberra
      libcap
      libclang.lib
      libdbusmenu
      libappindicator-gtk3
      libdrm
      libgcrypt
      libgpg-error
      libidn
      libjack2
      libjpeg
      libmikmod
      libogg
      libpng12
      libgccjit
      libglvnd
      libnotify
      libpulseaudio
      librsvg
      libsamplerate
      libthai
      libtheora
      libtiff
      libudev0-shim
      libsodium
      libssh
      libunwind
      libusb1
      libuuid
      libvdpau
      libvorbis
      libvpx
      libxcrypt-legacy
      libxkbcommon
      libxml2
      mesa
      nspr
      nss
      openssl
      p11-kit
      pango
      pixman
      python3
      speex
      pipewire
      stdenv.cc.cc
      tbb
      udev
      systemd
      util-linux
      vulkan-loader
      wayland
      libice
      libsm
      libx11
      libxscrnsaver
      libxcomposite
      libxcursor
      libxdamage
      libxext
      libxfixes
      libxft
      libxi
      libxinerama
      libxmu
      libxrandr
      libxrender
      libxt
      libxtst
      libxxf86vm
      libpciaccess
      libxcb
      libxcb-util
      libxcb-image
      libxcb-keysyms
      libxcb-render-util
      libxcb-wm
      xkeyboard-config
      xz
      zlib
    ];
  };

  environment.systemPackages = with pkgs; [
    neovim
    git
    wget
    lshw

    # Archives
    unrar
    unzip
    zip
    unar

    # CLI
    ripgrep
    fd
    jq

    squeezelite
    efibootmgr
    btrfs-progs
  ];
}
