# Session variables (SHELL, EDITOR, GOPATH, ...) come from Hjem via conf.d/hjem-env.fish.
# SSH_AUTH_SOCK, GPG_TTY, direnv and zoxide hooks come from NixOS.

fish_add_path -pPm $HOME/.local/bin $HOME/.bun/bin $HOME/.cargo/bin $GOPATH/bin

# pure
set -g pure_symbol_nixdevshell_prefix '󱄅'

if status is-interactive
    # Let pinentry follow the terminal/display this shell runs in.
    gpg-connect-agent updatestartuptty /bye >/dev/null

    # Generated by Nix from the Basix scheme.
    test -f $__fish_config_dir/themes/basix.theme; and fish_config theme choose basix

    # Better ls
    alias ls='eza --icons --group-directories-first -1'
    alias minimax="env NVIM_APPNAME=nvim-minimax nvim"
    alias pix="env PI_CODING_AGENT_DIR=$HOME/.pi/pix-agent pi"

    # Abbrs
    abbr nrs 'sudo nixos-rebuild switch --flake ~/nix-config'
    abbr lg lazygit
    abbr gd 'git diff'
    abbr ga 'git add .'
    abbr gc 'git commit -am'
    abbr gl 'git log'
    abbr gs 'git status'
    abbr gst 'git stash'
    abbr gsp 'git stash pop'
    abbr gp 'git push'
    abbr gpl 'git pull'
    abbr gsw 'git switch'
    abbr gsm 'git switch main'
    abbr gb 'git branch'
    abbr gbd 'git branch -d'
    abbr gco 'git checkout'
    abbr gsh 'git show'

    abbr l ls
    abbr ll 'ls -l'
    abbr la 'ls -a'
    abbr lla 'ls -la'

    # For jumping between prompts (OSC 133)
    function mark_prompt_start --on-event fish_prompt
        echo -en "\e]133;A\e\\"
    end

    function vterm_printf
        if begin
                [ -n "$TMUX" ]; and string match -q -r "screen|tmux" "$TERM"
            end
            # tell tmux to pass the escape sequences through
            printf "\ePtmux;\e\e]%s\007\e\\" "$argv"
        else if string match -q -- "screen*" "$TERM"
            # GNU screen (screen, screen-256color, screen-256color-bce)
            printf "\eP\e]%s\007\e\\" "$argv"
        else
            printf "\e]%s\e\\" "$argv"
        end
    end
end

# Unmanaged, machine-local config: extra PATHs, shell integrations not in nixpkgs, ...
test -f $__fish_config_dir/config.local.fish; and source $__fish_config_dir/config.local.fish
